### ISSUE TITLE
Basic variable declaration and arithmetic operations exercise

### ISSUE THREAD

**Issue by kishankarun** [pybites/rust-bite-exercises#19]
Please include the basic exercise starting with variable declarations and arithmetic operations also

**Comment by bbelderbos** [comment]
Sounds good!

**Comment by dpdresser** [comment]
Hey Bob, opened a pull request for this, happy to revise if you think the exercise should go in a different direction!

**Comment by bbelderbos** [comment]
Excellent, thanks! Also thanks Tanner for reviewing.
